package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_sass//:defs.bzl", "sass_binary", "sass_library")

sass_library(
    name = "common",
    srcs = [
        "_common.scss",
        "//src/gtk/sass/common/resources:key_colors",
    ],
)
