package(default_visibility = ["//visibility:public"])

# load("@io_bazel_rules_sass//:defs.bzl", "sass_library", "sass_binary")
# 
# # make a :colors target that any sass_binary rules can depend on.
# sass_library(
#     name = "colors",
#     srcs = ["common/_colors.scss"],
# )
# 
# # make a :fonts target that any sass_binary rules can depend on.
# sass_library(
#     name = "common",
#     srcs = ["common/_common.scss"],
# )
# 
# # make a :shared target that includes both :colors and :fonts.
# sass_library(
#     name = "shared",
#     srcs = [
#         ":colors",
#         ":common",
#     ],
# )
# 
# sass_binary(
# 	name = "4.0/mixed",
# 	src = "4.0/gtk-mixed.scss",
# 	deps = [
# 		"//src/gtk/sass:shared",
# 	],
# 	include_paths = [
# 		"common",
# 	],
# )
